Library/Models/BorrowingRecords.cs
using System.ComponentModel.DataAnnotations;

namespace Library.Models
{
    public class BorrowingRecords
    {
        private DateTime? borrowDateDelivery;

        public int Id { get; set; }

        public int BookId { get; set; }
        [Required(ErrorMessage = "Name is required")]
        public string BookName { get; set; } = string.Empty;
        [Required(ErrorMessage = "Type the title of the book")]
        public required string BookTitle { get; set; }
        [Required(ErrorMessage = "Type the description of the book")]
        public string BookDescription { get; set; } = string.Empty;
        public int PersonId { get; set; }
        [Required(ErrorMessage = "Type the name of the person")]
        public required string PersonName { get; set; }
        public DateTime BorrowDate { get; set; } = DateTime.Now;
        public DateTime BorrowDateDelivery { get; set; }
        public bool IsBorrowed { get; set; } = false;
    }
}

Library/Models/ErrorViewModel.cs
namespace Library.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Library/Controllers/BorrowingController.cs
using Library.Data;
using Library.Models;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
    public class BorrowingController : Controller
    {

        readonly private LibraryDbContext _db;

        public BorrowingController(LibraryDbContext db) {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<BorrowingRecords> borrowing = _db.BorrowingRecords;
            return View(borrowing);
        }

        public IActionResult NewBorrow()
        {
            return View();
        }
        [HttpPost]
        public IActionResult NewBorrow(BorrowingRecords borrowing)
        {
            if (ModelState.IsValid)
            {
                _db.BorrowingRecords.Add(borrowing);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult EditBorrow(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            BorrowingRecords borrow = _db.BorrowingRecords.FirstOrDefault(x => x.Id == id);

            if (borrow == null)
            {
                return NotFound();
            }
            return View(borrow);
        }
        [HttpPost]
        public IActionResult EditBorrow(BorrowingRecords borrowing)
        {
            if (ModelState.IsValid)
            {
                _db.BorrowingRecords.Update(borrowing);
                _db.SaveChanges();

                return RedirectToAction("Index");

            }
            return View(borrowing);
        }
        [HttpGet]
        public IActionResult DeleteBorrow(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }

            BorrowingRecords borrowing = _db.BorrowingRecords.FirstOrDefault(x => x.Id == id);

            if (borrowing == null)
            {
                return NotFound();
            }

            return View(borrowing);
        }
        [HttpPost]
        public IActionResult DeleteBorrow(BorrowingRecords borrowing)
        {
            if(borrowing == null)
            {
                return NotFound();
            }
            _db.BorrowingRecords.Remove(borrowing);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Library/Controllers/HomeController.cs
using System.Diagnostics;
using Library.Models;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Library/Views/Borrowing/DeleteBorrow.cshtml
@model Library.Models.BorrowingRecords

@{

    ViewData["title"] = "Delete Borrow";
}


<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h4 class="text-light">Delete Borrow</h4>
    </div>




    <hr />
    <div class="row">
        <div class="">
            <form asp-action="DeleteBorrow" asp-controller="Borrowing" method="post">
                <input type="hidden" asp-for=Id />

                <h2 class="text-light">Are you sure you want to delete this book</h2>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group mb-3">
                    <label asp-for="BookName" for="inputPassword5" class="form-label text-light"></label>
                    <input asp-for="BookName" class="form-control" disabled />
                    <span asp-validation-for="BookName" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="BookTitle" class="control-label text-light"></label>
                    <input asp-for="BookTitle" class="form-control" disabled />
                    <span asp-validation-for="BookTitle" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="BookDescription" class="control-label text-light"></label>
                    <input asp-for="BookDescription" class="form-control" disabled />
                    <span asp-validation-for="BookDescription" class="text-danger"></span>
                    @* </div>
                <div class="form-group mb-3">
                    <label asp-for="PersonId" class="control-label text-light"></label>
                <input asp-for="PersonId" class="form-control" />
                <span asp-validation-for="PersonId" class="text-danger"></span>
            </div> *@
                    <div class="form-group mb-3">
                        <label asp-for="PersonName" class="control-label text-light"></label>
                        <input asp-for="PersonName" class="form-control" disabled />
                        <span asp-validation-for="PersonName" class="text-danger"></span>
                    </div>



                    <div class="form-group">
                        <input type="submit" value="Delete" class="btn btn-danger" />
                    </div>
            </form>
        </div>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Library/Views/Borrowing/EditBorrow.cshtml
@model Library.Models.BorrowingRecords

@{
    
    ViewData["title"] = "Edit Borrow";
}


<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h4 class="text-light">Edit Borrow</h4>
    </div>




    <hr />
    <div class="row">
        <div class="">
            <form asp-action="EditBorrow" asp-controller="Borrowing" method="post">
                <input type="hidden" asp-for=Id />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group mb-3">
                    <label asp-for="BookName" for="inputPassword5" class="form-label text-light"></label>
                    <input asp-for="BookName" class="form-control" />
                    <span asp-validation-for="BookName" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="BookTitle" class="control-label text-light"></label>
                    <input asp-for="BookTitle" class="form-control" />
                    <span asp-validation-for="BookTitle" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="BookDescription" class="control-label text-light"></label>
                    <input asp-for="BookDescription" class="form-control" />
                    <span asp-validation-for="BookDescription" class="text-danger"></span>
                    @* </div>
                <div class="form-group mb-3">
                    <label asp-for="PersonId" class="control-label text-light"></label>
                <input asp-for="PersonId" class="form-control" />
                <span asp-validation-for="PersonId" class="text-danger"></span>
            </div> *@
                    <div class="form-group mb-3">
                        <label asp-for="PersonName" class="control-label text-light"></label>
                        <input asp-for="PersonName" class="form-control" />
                        <span asp-validation-for="PersonName" class="text-danger"></span>
                    </div>



                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-warning" />
                    </div>
            </form>
        </div>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Library/Views/Borrowing/Index.cshtml
@model IEnumerable<BorrowingRecords>

<div class="container">
    <div class="d-flex justify-content-between align-items-center mb-5">
        <h1>Borrowings</h1>
        <a class="btn btn-success mx-2" asp-controller="Borrowing" asp-action="NewBorrow">New Borrow</a>
    </div>

<table class="table table-striped">
    <tr>
        
        
        <th>BookName</th>
        <th>BookTitle</th>
        <th>Description</th>
        
        <th>PersonName</th>
        <th>BorrowDate</th>
        <th>BorrowDateDelivery</th>
        <th></th>
    </tr>

@if(Model != null){
    
        @foreach(var borrowing in Model)
        {
            <tr>
               
                
                <td>@borrowing.BookName</td>
                <td>@borrowing.BookTitle</td>
                <td>@borrowing.BookDescription</td>
                
                <td>@borrowing.PersonName</td>
                <td>@borrowing.BorrowDate</td>
                <td>@borrowing.BorrowDateDelivery </td>
               <td>
                        <a asp-controller="Borrowing" asp-action="EditBorrow" asp-route-id="@borrowing.Id" class="btn btn-warning mx-2">Edit</a>
                        <a asp-controller="Borrowing" asp-action="DeleteBorrow" asp-route-id="@borrowing.Id" class="btn btn-danger mx-2">Delete</a>
               </td>
            </tr>
        }
        
}


    
   
</table>
</div>

Library/Views/Borrowing/NewBorrow.cshtml
@model Library.Models.BorrowingRecords

@{
    Layout = "_Layout";
    ViewData["title"] = "New Borrow";
}


<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h4 class="text-light">New Borrow</h4>
    </div>




<hr />
<div class="row">
    <div class="">
        <form asp-action="NewBorrow" asp-controller="Borrowing" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group mb-3">
                    <label asp-for="BookName" for="inputPassword5" class="form-label text-light"></label>
                <input asp-for="BookName" class="form-control" />
                <span asp-validation-for="BookName" class="text-danger"></span>
            </div>
                <div class="form-group mb-3">
                    <label asp-for="BookTitle" class="control-label text-light"></label>
                <input asp-for="BookTitle" class="form-control" />
                <span asp-validation-for="BookTitle" class="text-danger"></span>
            </div>
                <div class="form-group mb-3">
                    <label asp-for="BookDescription" class="control-label text-light"></label>
                <input asp-for="BookDescription" class="form-control" />
                <span asp-validation-for="BookDescription" class="text-danger"></span>
            @* </div>
                <div class="form-group mb-3">
                    <label asp-for="PersonId" class="control-label text-light"></label>
                <input asp-for="PersonId" class="form-control" />
                <span asp-validation-for="PersonId" class="text-danger"></span>
            </div> *@
                <div class="form-group mb-3">
                    <label asp-for="PersonName" class="control-label text-light"></label>
                <input asp-for="PersonName" class="form-control" />
                <span asp-validation-for="PersonName" class="text-danger"></span>
            </div>
            
            
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Library/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Library.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Library</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Borrowing" asp-action="Index">Emprestimo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Library - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>